//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

//side menu
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU';
export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU';

//update user profile
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_RESPONSE = 'UPDATE_USER_PROFILE_RESPONSE';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';
export const UPDATE_USER_PROFILE_INFO = 'UPDATE_USER_PROFILE_INFO';
